import Head from "next/head";

import { client } from "../lib/client";
import { Products, FooterBanner, HeroBanner } from "../components";

export default function Home({ products, bannerData }) {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta
          name="description"
          content="Ecommerce website generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
      <div className="products-heading">
        <h2>Best Selling Products</h2>
        <p>Speakers of many variations</p>
      </div>
      <div className="products-container">
        {products?.map((product) => (
          <Products key={product.id} product={product} />
        ))}
      </div>
      <FooterBanner />
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);
  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
